# 十四、Q

我是一个有想法的人。努力工作不是我的强项。—Q，星际迷航:航海家

JavaScript 是一种异步语言。无论是在浏览器中还是在服务器上，开发人员都可以指示 JavaScript 运行时“调度”代码在未来某个时间点运行。该特性通常用于延迟 CPU 密集型或长时间运行的操作的开始，让应用有时间完成其当前任务，然后再继续执行更耗费人力的任务。这个特性如此强大，以至于传统的同步语言如 Java、C#、PHP 和 Ruby 都纷纷效仿并采用了它。一些语言，比如 C#，已经实现了异步执行模型作为一种语言特性(通过`async`和`await`关键字)；其他语言，如 PHP，支持与 React 等外部库的异步性(不要与 FaceBoook 的 JavaScript 库 React 混淆)。无论哪种情况，异步代码和同步代码都必然会相遇。

q 是一个 JavaScript 库，它封装了接口背后的异步行为，读起来很像同步代码，这是本章的主题。q 产生承诺，可以链接在一起的特殊对象，以消除嵌套的回调，传播值和错误，并通常在异步代码中管理流控制。然而，在深入探讨 Q 之前，有必要走一小段弯路，研究一下为什么异步代码难以编写和管理。

## 时机就是一切

同步代码非常容易阅读，因为计算机一次执行一条语句。由同步代码(例如，通过方法调用)生成的返回值在返回后立即可供调用代码使用。具有结构化异常处理特性的语言提供了`try/catch/finally`块，可以用来预测和处理出现的错误，这样微不足道的(或可恢复的)错误就不会对应用造成致命影响。但是结构化异常处理只适用于同步代码；它的行为类似于一个`goto`语句，导致代码“跳转”到应用中的某个其他点，并在该点继续执行语句。

异步代码的行为稍有不同。在 JavaScript 中，异步代码被安排在未来的某个时间点运行(有时就在当前正在执行的代码之后)。这打破了同步模型，因为未来的代码将只在当前堆栈展开后运行。那么，在异步代码中创建的返回值和错误也必须在将来代码实际运行时进行处理。

许多语言(包括 JavaScript)都用回调来解决这个问题，回调是作为异步代码的参数传递的函数，一旦代码运行，就调用这些函数来处理错误和“返回值”Node.js 运行时严重依赖 JavaScript 的调度功能，它甚至为所有回调函数指定了标准签名，以便正确处理和传播异步错误。

不幸的是，嵌套的异步代码会很快变得复杂。考虑清单 14-1 中的例子。

Listing 14-1\. Asynchronous Node.js Example

`// example-001/index.js`

`'use strict';`

`var fs = require('fs');`

`var path = require('path');`

`var playerStats = require('./player-stats');`

`function getPlayerStats(gamesFilePath, playerID, cb) {`

`// fs.readFile() is asynchronous`

`fs.readFile(gamesFilePath, {encoding: 'utf8'}, function (err, content) {`

`if (err) {`

`return cb(err);`

`}`

`var games = JSON.parse(content);`

`var playerGames = games.filter(function (game) {`

`return game.player === playerID;`

`});`

`// playerStats.calcBest() is asynchronous`

`playerStats.calcBest(playerGames, function (err, bestStats) {`

`if (err) {`

`return cb(err);`

`}`

`// playerStats.calcAvg() is asynchronous`

`playerStats.calcAvg(playerGames, function (err, avgStats) {`

`if (err) {`

`return cb(err);`

`}`

`cb(null, {best: bestStats, avg: avgStats});`

`});`

`});`

`});`

`}`

`var gamesFilePath = path.join(__dirname, 'games.json');`

`getPlayerStats(gamesFilePath, 42, function (err, stats) {`

`if (err) {`

`console.error(err);`

`return process.exit(1);`

`}`

`console.log('best:', stats.best);`

`console.log('avg: ', stats.avg)`

`});`

在本例中，JavaScript 代码被调度了四次:

The declaration and invocation of `getPlayerStats()`   The invocation of `fs.readFile()`   The invocation of `playerStats.calcBest()`   The invocation of `playerStats.calcAvg()`  

很容易想象`playerStats`可能是一个对查询响应缓慢的外部服务。但是如果这段代码是同步的，如清单 14-2 所示，所有的事情都会被调度一次。每个函数和方法都将按顺序被调用，所有这些都被分组到一个`try/catch`块中以处理任何同步错误，并且统计数据将在收到时被写入控制台。

Listing 14-2\. Synchronous Node.js Example

`// example-002/index.js`

`'use strict';`

`var fs = require('fs');`

`var path = require('path');`

`var playerStats = require('./player-stats');`

`try {`

`var gamesFilePath = path.join(__dirname, 'games.json');`

`// fs.readFileSync() is synchronous`

`var content = fs.readFileSync(gamesFilePath, {encoding: 'utf8'});`

`var games = JSON.parse(content);`

`var playerGames = games.filter(function (game) {`

`return game.player === 42;`

`});`

`// playerStats.calcBestSync() is synchronous`

`console.log('best:', playerStats.calcBestSync(playerGames));`

`// playerStats.calcAvgSync() is synchronous`

`console.log('avg :', playerStats.calcAvgSync(playerGames));`

`} catch (e) {`

`console.error(e);`

`process.exit(1);`

`}`

这个同步例子更容易理解，尽管每个语句在完成之前都会阻塞执行流程。异步回调驱动的代码虽然减轻了这个缺点，但仍然有许多严重的问题。

首先，没有回调签名必须遵守的真正规范的标准。Node.js 约定是被最广泛采用的，但是模块作者可以(并且确实)创建不遵循该标准的 API。当 JavaScript 模块包装或模拟现有的非 JavaScript API 时，通常会发生这种情况。为了熟悉 Node.js 约定，模块作者可能会决定模仿该 API 的回调签名模式。

第二，回调手动传播错误。每个回调都必须检查`err`对象，并决定如何处理它，或者将它转发给另一个执行相同操作的回调。结果往往是许多样板错误检查代码。在同步代码中，异常会自动在堆栈中向上传播，直到被一个`catch`块处理。

也很容易遗漏或不恰当地处理异步代码中出现的同步错误。在清单 14-3 中，`try/catch`块包装同步`JSON.parse`调用，然后在成功时传播解析的 JavaScript 对象，或者在解析失败时传播捕获的异常。

Listing 14-3\. Improperly Invoking a Callback Within a `try/catch` Block

`// example-003/improper-async-error-handling.js`

`'use strict';`

`var fs = require('fs');`

`var path = require('path');`

`function readJSONFile(filePath, cb) {`

`fs.readFile(filePath, function (err, buffer) {`

`try {`

`var json = JSON.parse(buffer.toString());`

`cb(null, json);`

`} catch (e) {`

`console.log('where did this error come from?', e.message);`

`cb(e);`

`}`

`});`

`}`

`var gamesFilePath = path.join(__dirname, 'games.json');`

`readJSONFile(gamesFilePath, function (err, json) {`

`if (err) {`

`return console.error('parsing json did not succeed :(');`

`}`

`console.log('parsing json was successful :)');`

`throw new Error('should never happen, right?');`

`});`

假设`games.json`文件存在，并且有有效的 JSON 数据。在这个例子中，在数据被解析之后，回调将在`try`块中被调用。但是请注意当回调中抛出异常时会发生什么。这个异常会将堆栈展开回到`try`块中，并导致`catch`块捕获该异常，再次调用回调，并返回回调生成的完全相同的错误。这可能会产生意想不到的后果。如清单 14-4 所示，处理这个错误的适当方法是避免在`try/catch`块中调用回调。

Listing 14-4\. Improperly Invoking a Callback Within a `try/catch` Block

`// example-003/proper-async-error-handling.js`

`'use strict';`

`var fs = require('fs');`

`var path = require('path');`

`function readJSONFile(filePath, cb) {`

`fs.readFile(filePath, function (err, buffer) {`

`var json, err;`

`try {`

`json = JSON.parse(buffer.toString());`

`} catch (e) {`

`err = e;`

`}`

`if (err) {`

`console.log('where did this error come from?', e.message);`

`return cb(err);`

`}`

`cb(null, json);`

`});`

`}`

`var gamesFilePath = path.join(__dirname, 'games.json');`

`readJSONFile(gamesFilePath, function (err, json) {`

`if (err) {`

`return console.error('parsing json did not succeed :(');`

`}`

`console.log('parsing json was successful :)');`

`throw new Error('should never happen, right?');`

`});`

最后，嵌套回调是一把双刃剑。一方面，每个回调都可以访问它自己的闭包和包围它的闭包中的数据；另一方面，嵌套很快导致复杂和紧密耦合的代码。程序的真正流程可能会变得模糊不清，产生一个不可维护的生态系统，容易滋生 bug。

## 承诺与回访

为了减轻异步回调带来的挑战，JavaScript 社区的成员起草了许多建议和规范，最终形成了 Promises/A+规范。该规范以及其他相关规范定义了一种方法，将异步操作封装在一个称为“promise”的特殊对象中，该对象可以与其他承诺相结合，创建一种异步链，通过该链可以传播值和错误，并在必要时进行处理。

根据 Promises/A+规范的定义，承诺用三种状态表示其异步操作:挂起、完成和拒绝。如果我们从回调的角度考虑这个问题，它将对应于清单 14-5 。

Listing 14-5\. Callback Equivalents to Promise States

`// invoking the function means the operation is "pending"`

`asyncFunction(function asyncCallback (err, asyncData) {`

`if (err) {`

`// if an error occurred the operation is "rejected"`

`}`

`// otherwise the operation is "fulfilled"`

`});`

promise 也称为“thenable ”,因为它有一个接受两个可选回调的`then()`方法:第一个在 promise 的异步操作完成时调用，第二个在操作被拒绝时调用。完整签名显示在清单 14-6 中。

Listing 14-6\. Thenable Method Signature

`/**`

`* @param {Function} [onFulfilled]`

`* @param {Function} [onRejected]`

`* @returns {Promise}`

`*/`

`promise.then(onFulfilled, onRejected)`

但是等等！承诺的全部意义不就是消除回调吗？不，承诺的要点是简化将异步操作链接在一起的过程，这个过程通常会将开发人员引向嵌套回调的道路。注意，promise 的`then()`方法实际上也返回了一个承诺。这个承诺也将根据原始承诺的回调中发生的情况要么被履行，要么被拒绝。通过利用这个特性，可以重写清单 14-7 中的玩家统计代码，以几乎消除嵌套。

Listing 14-7\. Promises Reduce Nesting

`// example-004/index.js`

`'use strict';`

`var fs = require('fs');`

`var path = require('path');`

`var playerStats = require('./player-stats');`

`var Q = require('q');`

`function getPlayerStats(gamesFilePath, playerID, cb) {`

`// load() returns a promise`

`playerStats.load(gamesFilePath, playerID)`

`.then(function (games) {`

`// Q.all() returns a promise`

`return Q.all([`

`// calcBest() returns a promise`

`playerStats.calcBest(games),`

`// calcAvg() returns a promise`

`playerStats.calcAvg(games)`

`]);`

`})`

`.done(function (allStats) {`

`cb(null, {best: allStats[0], avg: allStats[1]});`

`}, function (err) {`

`cb(err);`

`});`

`}`

`var gamesFilePath = path.join(__dirname, 'games.json');`

`getPlayerStats(gamesFilePath, 42, function (err, stats) {`

`if (err) {`

`console.error(err);`

`return process.exit(1);`

`}`

`console.log('best:', stats.best);`

`console.log('avg: ', stats.avg)`

`});`

在清单 14-7 中，只有最后的`done()`调用接收解析和拒绝回调；所有其他调用只接收一个解析回调(来自`playerStats`模块的函数)。被连续调用的变量称为承诺链。如果这些中间的`then()`调用之一产生了错误，会发生什么呢？与异步回调模型不同，promises 将通过 promise 链自动传播错误，直到错误被处理(类似于结构化异常处理)。有一些特定的规则和用例可以改变这种行为，但一般来说，它完全按照人们的预期工作。

这个例子的其他有趣的方面将在后面解释(比如实现和拒绝回调的返回值如何影响承诺链)。然而，很明显，承诺可以减少回调嵌套和自动化错误传播，这是异步 JavaScript 代码中出现的两个主要问题。

## 阿 q 的承诺

q 是一个开源的 JavaScript 库，它实现了 Promises/A+规范，但它并不是开发者唯一可用的库。其他几个库，如 when.js 和 Bluebird，也提供了这些名称，这是一个值得注意的事实，因为该规范声明的目标是提供“一个可互操作的基础，所有 Promises/A+符合 promise 的实现都可以依赖这个基础来提供。”这意味着任何符合规范的 promise 库都可以与任何其他符合规范的库一起使用。开发者不必被迫在一系列竞争对手中做出选择。大多数有前途的库都提供辅助功能来补充核心的可移植接口。开发者可以根据需要自由选择和混合解决不同问题的 promise 库。(不幸的是，不符合 Promises/A+规范的库，比如 jQuery。延期，不会这样整合。)

q 是本章的主题，有几个强有力的理由:

*   它符合 Promises/A+规格。
*   它是由 Kris Kowal 写的，他是规范的一个贡献者。
*   它在 JavaScript 社区(客户端和服务器端)享有广泛的采用和支持。
*   谷歌支持的流行浏览器框架 AngularJS 大量借鉴了 q。

本章的其余部分将根据异步回调驱动代码上的承诺来研究 Q 的实现。

### 延期和承诺

虽然 Promises/A+规范定义了可命名对象的行为方式，但它并没有明确说明异步操作应该如何触发提供给可命名对象的回调。它只定义了表示承诺中异步操作状态的规则，以及值和错误如何通过承诺链传播。实际上，许多 promise 库使用一个名为 deferred 的对象来操纵 promise 的状态。延迟通常是首先创建的，连接起来处理异步操作的解析，然后生成一个承诺供以后调用代码使用。清单 14-8 展示了如何创建一个延期并返回它的承诺。

Listing 14-8\. Creating a Deferred

`var Q = require('q');`

`function asyncFunc() {`

`// create a deferred`

`var d = Q.defer();`

`// perform some async operation and`

`// manipulate the *deferred*`

`// return the deferred’s promise`

`return d.promise;`

`}`

`// the function returns a thenable!`

`asyncFunc().then(function () {`

`// success :)`

`}, function () {`

`// error :(`

`});`

在清单中，14-8 `Q.defer()`被调用来创建一个延迟对象，当异步代码实际运行时，这个延迟对象将被用来在将来操纵承诺的状态(稍后会详细介绍)。这里重要的是被延迟的拥有一个承诺——一个从`asyncFunc()`返回的承诺，通过调用它的`then()`方法可以将回调附加到该承诺上。对`asyncFunc()`的实际调用和对返回承诺的状态更改的订阅都被安排在一起。然而`asyncFunc()`选择解决还是拒绝它的延期(从而改变承诺返回的状态)完全取决于开发者。

清单 14-9 是前面提到的虚构的`playerStats`模块的`calcAvg()`函数的简单实现。使用归约运算对一系列数字求和，然后除以序列长度(得出平均值)是一种同步运算。为了使其异步，代码被包装在 Node.js 函数`process.nextTick()`中，该函数调度代码在事件循环的下一次迭代中运行。(用`setTimeout()`或`setImmediate()`也可以完成同样的操作。)如果计算成功，则使用`d.resolve()`将承诺置于 resolved 状态，该状态接受一些要传递给任何附加到承诺的解析回调的值。同样，如果出现错误(例如，`games`数组的长度为零，产生一个被零除的错误)，promise 通过`d.reject()`被置于拒绝状态。

Listing 14-9\. Using a Deferred in the `calcAvg()` Implementation

`// example-004/player-stats.js`

`var Q = require('q');`

`module.exports = {`

`// load: function (gamesFilePath, playerID) {...}`

`// calcBest: function (games) {...},`

`calcAvg: function (games) {`

`var stats = {`

`totalRounds: 0,`

`avgRoundsWon: 0,`

`avgRoundsLost: 0`

`};`

`var deferred = Q.defer();`

`process.nextTick(function () {`

`if (games.length === 0) {`

`deferred.reject(new Error('no games'));`

`return;`

`}`

`var wins = 0, losses = 0;`

`games.forEach(function (game) {`

`if (game.rounds === 0) return;`

`stats.totalRounds += game.rounds;`

`wins += game.won;`

`losses += game.lost;`

`});`

`stats.avgRoundsWon = (wins / stats.totalRounds * 100)`

`.toFixed(2) + '%';`

`stats.avgRoundsLost = (losses / stats.totalRounds * 100)`

`.toFixed(2) + '%';`

`deferred.resolve(stats);`

`});`

`return deferred.promise;`

`}`

`};`

清单 14-10 展示了延迟和承诺如何被用来包装异步的回调驱动的 API。

Listing 14-10\. Using a Deferred to Wrap an Asynchronous, Callback-Driven API

`// example-005/callbackdb/database.js`

`'use strict';`

`module.exports = {`

`customer: {`

`// requires a callback`

`find: function (criteria, cb) {`

`cb(null, {`

`id: criteria.id,`

`name: 'Nicholas Cloud'`

`});`

`}`

`}`

`};`

`// example-005/callbackdb/find-customer-callback.js`

`var Q = require('q'),`

`db = require('./database');`

`function loadCustomer(customerID) {`

`var d = Q.defer();`

`// db.customer.find() is asynchronous`

`db.customer.find({id: customerID}, function (err, customer) {`

`if (err) {`

`return d.reject(err);`

`}`

`d.resolve(customer);`

`});`

`return d.promise;`

`}`

`loadCustomer(1001).then(function (customer) {`

`console.log('found', customer.id, customer.name);`

`}, function (err) {`

`console.error(err);`

`});`

这种包装异步代码的模型非常普遍，事实上，Q 提供了许多方便的方法来减轻编写样板代码的负担。q 的延迟对象有一个`makeNodeResolver()`方法，当被调用时，创建一个伪回调，可以传递给任何标准的基于异步回调的函数。然而，当这个回调被调用时，它只是用适当的值或错误来改变 deferred 的状态，无论哪一个恰好被传递给回调。清单 14-11 展示了一个解析器如何取代手工编写的回调函数。

Listing 14-11\. Making a Node Resolver Callback

`// example-005/callbackdb/database.js`

`'use strict';`

`module.exports = {`

`customer: {`

`// requires a callback`

`find: function (criteria, cb) {`

`cb(null, {`

`id: criteria.id,`

`name: 'Nicholas Cloud'`

`});`

`}`

`}`

`};`

`// example-005/callbackdb/find-customer-makenoderesolver.js`

`var Q = require('q'),`

`db = require('./database');`

`function loadCustomer(customerID) {`

`var d = Q.defer();`

`// db.customer.find() is asynchronous`

`var deferredCallback = d.makeNodeResolver();`

`db.customer.find({id: customerID}, deferredCallback);`

`return d.promise;`

`}`

`loadCustomer(2001).then(function (customer) {`

`console.log('found', customer.id, customer.name);`

`}, function (err) {`

`console.error(err);`

`});`

在这种情况下，调用`loadCustomer()`的客户端代码期望一个承诺，但是数据库 API 期望一个回调，所以`makeNodeResolver()`自然适合。如果反过来也是正确的——如果客户端代码期望将回调传递给`loadCustomer()`函数，但是数据库实际上返回了一个承诺——对数据库的承诺调用`nodeify()`方法将适当地调用回调。清单 14-12 中的承诺正是以这种方式实现的。

Listing 14-12\. Passing a Traditional Asynchronous Callback to a Promise with `nodeify()`

`// example-005/promisedb/database.js`

`'use strict';`

`var Q = require('q');`

`module.exports = {`

`customer: {`

`// returns a promise; does not use callbacks`

`find: function (criteria) {`

`return Q({`

`id: criteria.id,`

`name: 'Nicholas Cloud'`

`});`

`}`

`}`

`};`

`// example-005/promisedb/find-customer-nodeify.js`

`var Q = require('q'),`

`db = require('./database');`

`function loadCustomer(customerID, cb) {`

`// db.customer.find() returns a promise`

`db.customer.find({id: customerID})`

`.nodeify(cb);`

`/* equivalent to:`

`*`

`* db.customer.find({id: customerID}).then(function (customer) {`

`*   cb(null, customer);`

`* }, function (err) {`

`*   cb(err);`

`* });`

`*/`

`}`

`loadCustomer(3001, function (err, customer) {`

`if (err) {`

`return console.err(err);`

`}`

`console.log('found', customer.id, customer.name);`

`});`

### 值和错误

用简单的值或错误来解决延迟问题通常可以满足大多数需求，但是 Promises/A+规范和 Q 的实现定义了许多 promise 解决规则，让开发人员可以进一步控制 promise 状态。

#### 用承诺值解决延期

延迟的行为会根据传递给它们的`resolve()`方法的“值”而改变。如果该值是一个普通对象或原语，它将按原样传递给附属于延期者承诺的解析回调。如果“值”是另一个承诺，如清单 14-13 所示，第二个承诺的状态将被“转发”给第一个承诺的适当回调:如果第二个承诺被解析，第一个承诺的解析回调将接收它的值；如果它被拒绝，第一个的拒绝回调将收到它的错误。

Listing 14-13\. Resolving a Deferred with a Promise

`// example-006/index.js`

`'use strict';`

`var Q = require('q'),`

`airport = require('./airport'),`

`reservation = require('./reservation');`

`function findAvailableSeats(departingFlights) {`

`var d = Q.defer();`

`process.nextTick(function () {`

`var availableSeats = [];`

`departingFlights.forEach(function (flight) {`

`var openFlightSeats = reservation.findOpenSeats(flight);`

`availableSeats = availableSeats.concat(openFlightSeats);`

`});`

`// resolve the deferred with an object value`

`if (availableSeats.length) {`

`d.resolve(availableSeats);`

`} else {`

`d.reject(new Error('sorry, no seats available'));`

`}`

`});`

`return d.promise;`

`}`

`function lookupFlights(fromAirport, toAirport, departingAt) {`

`var d = Q.defer();`

`process.nextTick(function () {`

`var departingFlights = airport.findFlights(`

`fromAirport, toAirport, departingAt`

`);`

`// resolve the deferred with another promise`

`d.resolve(findAvailableSeats(departingFlights));`

`});`

`return d.promise;`

`}`

`lookupFlights('STL', 'DFW', '2015-01-10').then(function (seats) {`

`console.log('available seats:', seats);`

`}, function (err) {`

`console.error('sorry:', err);`

`});`

因为第一个延迟最终取决于第二个承诺的解决或拒绝，所以只要第二个承诺也是未决的，它就将保持未决状态。一旦第二个承诺被解决或拒绝，被推迟的承诺也会跟着做，调用适当的回调。

#### 在回调中转发值、错误和承诺

一旦解析或拒绝回调收到一个值或错误，就会发生几件事。如果已经到达承诺链的末尾(或者如果没有其他链接的承诺)，通常客户端代码会对该值做一些事情或者记录错误。

然而，因为当调用`then()`时，变量总是返回另一个承诺，所以可以使用解析和拒绝回调来操作值和错误，然后将它们转发给新的承诺，由后面的回调来处理。

操作一个值非常简单。只需改变或转换传递给解析回调的值并返回它。在清单 14-14 中，一个数组在数据库承诺的解析回调中被操作，然后在值被适当过滤后被返回。

Listing 14-14\. Returning a Value in a Resolution Callback

`// example-007/index.js`

`'use strict';`

`var db = require('./database');`

`function findPalindromeNames() {`

`// db.customers.find() returns a promise`

`return db.customer.find().then(function (customers) {`

`// return a filtered array that will be forwarded`

`// to the next resolution callback`

`return customers.filter(function (customer) {`

`// filter customers with palindrome names`

`var name = customer.name.toLowerCase();`

`var eman = name.split('').reverse().join('');`

`return name === eman;`

`}).map(function (customer) {`

`// return only customer names`

`return customer.name;`

`});`

`});`

`}`

`findPalindromeNames().then(function (names) {`

`console.log(names);`

`});`

解析回调也可以将错误转发到承诺链的下游。如果是，那么将调用下一个拒绝回调，并返回错误。在清单 14-15 中，如果用户提交了太多的猜测(对于一些虚构的竞赛)，就会创建一个错误，并在一个名称的解析回调中抛出。该错误将传播到承诺链中的下一个拒绝回调。

Listing 14-15\. Throwing an Error in a Resolution Callback

`// example-008/index.js`

`'use strict';`

`var db = require('./database');`

`var MaxGuessError = require('./max-guess-error');`

`var MAX_GUESSES = 5;`

`function submitGuess(userID, guess) {`

`// db.user.find() returns a promise`

`return db.user.find({id: userID}).then(function (user) {`

`if (user.guesses.length === MAX_GUESSES) {`

`throw new MaxGuessError(MAX_GUESSES);`

`}`

`// otherwise update the user...`

`});`

`}`

`submitGuess(1001, 'Professor Plum').then(function () {`

`// won’t get called if there is an error`

`console.log('guess submitted');`

`}, function (maxGuessError) {`

`// oops, an error occurred!`

`console.error('invalid guess');`

`console.error(maxGuessError.toString());`

`});`

回想一下，在传统的异步回调模型中，抛出的异常必须手动处理和解释(这意味着不可预测的异常通常会逃过审查)。q 自动处理这个；在可调用回调中抛出的任何异常都将被捕获并适当地传播，即使所有可调用回调都是异步执行的。

拒绝回电遵循类似的规则，但有一个心理扭曲。他们不接受价值观；相反，它们会收到错误，所以开发人员可能会合理地期望从拒绝回调返回错误会触发承诺链下游的下一个拒绝回调。但这是不正确的。在清单 14-16 中，链中的最后一个承诺将被解决，而不是被拒绝，即使从`submitGuess()`中的拒绝回调返回一个错误。

Listing 14-16\. Returning an Error in a Rejection Callback

`// example-009/index.js`

`'use strict';`

`var db = require('./database');`

`var NotFoundError = require('./not-found-error');`

`function submitGuess(userID, guess) {`

`// db.user.find() returns a promise`

`return db.user.find({id: userID}).then(function (user) {`

`/*`

`* database generates an error so this promise`

`* won’t be resolved`

`*/`

`}, function (err) {`

`var notFoundError = new NotFoundError(userID);`

`notFoundError.innerError = err;`

`return notFoundError;`

`});`

`}`

`submitGuess(1001, 'Colonel Mustard').then(function (value) {`

`/*`

`* oops, this promise was resolved, and`

`* value === notFoundError!`

`*/`

`console.log('guess submitted');`

`console.log(value);`

`}, function (notFoundError) {`

`/*`

`* you expect this promise to get rejected...`

`* but you are wrong`

`*/`

`console.error('an error occurred');`

`console.error(notFoundError);`

`});`

这似乎违反直觉。如果从拒绝回调中返回一个错误，人们可能会合理地认为它会传播，但事实并非如此。然而，再一看，这开始有意义了，因为它允许开发人员处理不需要传播的错误，并且仍然通过返回一些值来优雅地解决承诺链。

如果清单 14-16 中的代码被修改为当数据库变得不可用时对猜测进行排队，那么即使产生了错误，解析承诺链也是有意义的，如清单 14-17 所示。

Listing 14-17\. Muffling an Error in a Rejection Callback

`// example-010/index.js`

`'use strict';`

`var db = require('./database');`

`var guessQueue = require('./guess-queue');`

`function submitGuess(userID, guess) {`

`// db.user.find() returns a promise`

`return db.user.find({id: userID}).then(function (user) {`

`/*`

`* database generates an error so this promise`

`* won’t be resolved`

`*/`

`}, function (err) {`

`console.error(err);`

`/*`

`* database is probably offline, queue for future`

`* processing`

`*/`

`return guessQueue.enqueue(userID, guess);`

`});`

`}`

`submitGuess(1001, 'Miss Scarlett').then(function (value) {`

`/*`

`* guess is queued when the database connection`

`* fails, so the error is suppressed`

`*/`

`console.log('guess submitted');`

`}, function (notFoundError) {`

`console.error('an error occurred');`

`console.error(notFoundError);`

`});`

与解析回调一样，为了正确地将下一个承诺的状态设置为 rejected，必须在拒绝回调中抛出错误，如清单 14-18 所示。

Listing 14-18\. Throwing an Error in a Rejection Callback

`// example-011/index.js`

`'use strict';`

`var db = require('./database');`

`var NotFoundError = require('./not-found-error');`

`function submitGuess(userID, guess) {`

`// db.user.find() returns a promise`

`return db.user.find({id: userID}).then(function (user) {`

`/*`

`* database generates an error so this promise`

`* won’t be resolved`

`*/`

`}, function (err) {`

`/*`

`* error is *thrown*, not returned`

`*/`

`var notFoundError = new NotFoundError(userID);`

`notFoundError.innerError = err;`

`throw notFoundError;`

`});`

`}`

`submitGuess(1001, 'Mrs. Peacock').then(function (value) {`

`/*`

`* since error was thrown within the promise`

`* the promise will not be resolved`

`*/`

`}, function (notFoundError) {`

`/*`

`* the promise is rejected, as expected!`

`*/`

`console.error('an error occurred');`

`console.error(notFoundError);`

`});`

正如延迟可以用其他承诺来解决一样，启用回调也可以返回承诺，当这些承诺被解决或拒绝时，将会影响回调链的状态。解决和拒绝回调都可能返回承诺。在清单 14-19 中，如果数据库调用成功，则返回第二个承诺，否则抛出异常。

Listing 14-19\. Returning Another Promise in a Resolution Callback

`// example-012/index.js`

`'use strict';`

`var db = require('./database');`

`var MaxGuessError = require('./max-guess-error');`

`var MAX_GUESSES = 5;`

`function submitGuess(userID, guess) {`

`// db.user.find() returns a promise`

`return db.user.find({id: userID}).then(function (user) {`

`if (user.guesses.length === MAX_GUESSES) {`

`throw new MaxGuessError(MAX_GUESSES);`

`}`

`// otherwise update the user`

`user.guesses.push(guess);`

`return db.user.update(user);`

`});`

`}`

`submitGuess(1001, 'Professor Plum').then(function () {`

`/*`

`* should be called with the database has`

`* finished updating the user`

`*/`

`console.log('guess submitted');`

`}, function (maxGuessError) {`

`console.error('invalid guess');`

`console.error(maxGuessError.toString());`

`});`

#### 将简单的价值观转化为承诺

q 可以将任何值转化为承诺，只需调用`Q`作为函数，并将值作为唯一的参数。清单 14-20 包装了一个简单的字符串，该字符串将被用作传递给承诺链中下一个解析处理程序的值。

Listing 14-20\. Turning a Value into a Promise

`// example-013/index.js`

`'use strict';`

`var Q = require('q');`

`Q('khan!').then(function (value) {`

`console.log(value); //khan!`

`});`

这可能看起来微不足道，但是这是将现有的、带有实际返回值的同步代码包装到基于 promise 的 API 中的一种便捷方式。您可以不带值地调用`Q`，这将创建一个处于已解决状态的空承诺。

用另一个库的承诺调用`Q`,也会将该承诺包装在 Q 的接口中。当开发人员在处理另一个没有对等物的 promise 库时，希望使用 Q 的 promise 方法如`nodeify()`时，这非常有用。

### 报告进度

有时异步操作需要很长时间才能完成。在此期间，向客户端代码提供一些进度指示可能会有所帮助，无论是作为简单的指示器(例如，完成百分比)，还是在数据可用时交付它们(例如，由 EventEmitter 引发的事件)。q 通过向`then()`添加第三个回调参数来扩充 Promises/A+规范，如清单 14-21 所示，该参数可用于在进度事件发生时捕获它们。

Listing 14-21\. Q’s Thenable Method Signature

`/**`

`* @param {Function} [onFulfilled]`

`* @param {Function} [onRejected]`

`* @param {Function} [onProgress]`

`* @returns {Promise}`

`*/`

`promise.then(onFulfilled, onRejected, onProgress)`

虽然 Promises/A+规范没有为进度通知建立模式，但是 Q 仍然符合，因为它的所有名称仍然支持规定的`then()`方法签名。

正如实现和拒绝回调在延迟的被实现或拒绝时被调用一样，进度回调在延迟的`notify()`方法被调用时也被调用。该方法接受单个参数，然后将该参数传递给进度回调。在清单 14-22 中，一个长时间运行的异步操作跟踪它做一些工作的尝试次数(也许调用一个经常没有响应的 API)。每次尝试时，计数器都会递增，其值会传递给`notify()`方法。进度回调立即接收这些数据。一旦解决了延迟，承诺链就完成了，最后的`done()`回调被调用。

Listing 14-22\. Notifying the Deferred’s Promise

`<!-- example-014/index.html -->`

`<form>`

`<p>The UI thread should respond to text field input, even though many DOM elements are being added.</p>`

`<input type="text" placeholder="type something here" />`

`</form>`

`<div id="output"></div>`

`<script>`

`(function () {`

`var Q = window.Q;`

`var output = document.querySelector('#output');`

`function writeOutput(msg) {`

`var pre = document.createElement('pre');`

`pre.innerHTML = msg;`

`output.insertBefore(pre, output.firstChild);`

`}`

`function longAsync() {`

`var d = Q.defer();`

`var attempts = 0;`

`var handle = setInterval(function () {`

`// each time the scheduled code runs,`

`// send a notification with the attempt`

`// number`

`attempts += 1;`

`d.notify(attempts);`

`if (attempts === 1200) {`

`clearInterval(handle);`

`return d.resolve();`

`}`

`}, 0);`

`return d.promise;`

`}`

`// not using the rejection callback, only the`

`// resolution and progress callbacks`

`longAsync().then(function () {`

`writeOutput('(done)');`

`}, null, function (attempts) {`

`writeOutput('notification: ' + attempts);`

`});`

`}());`

`</script>`

值得注意的是，虽然任何附加到可调用对象的解析或拒绝回调都将根据承诺链中已经发生的情况来调用，但只有那些在通知事件之前附加的进度回调才会实际接收到更新。考虑清单 14-23 中的代码和清单 14-24 中产生的控制台输出。

Listing 14-23\. Notifying a Deferred’s Promise Before Progress Callback Is Added

`// example-015/index.js`

`'use strict';`

`var Q = require('q');`

`function brokenPromise() {`

`var d = Q.defer();`

`process.nextTick(function () {`

`console.log('scheduled first');`

`d.notify('notifying');`

`d.resolve('resolving');`

`console.log('logging');`

`});`

`return d.promise;`

`}`

`var promise = brokenPromise();`

`process.nextTick(function () {`

`console.log('scheduled second');`

`promise.then(function (value) {`

`console.log(value);`

`}, null, function (progress) {`

`console.log(progress);`

`});`

`});`

在清单 14-23 中，一个延迟被创建，然后被异步通知和解析。只有在 deferred 的方法被调用之后，回调才会被附加到`then()`。清单 14-24 中的控制台输出反映了代码作为 Node.js 脚本运行时发生的情况。

Listing 14-24\. Console Output Without Notification

`$ node index.js`

`scheduled first`

`logging`

`scheduled second`

`resolving`

`logging`语句显示在`notifying`或`resolving`之前，因为当函数`brokenPromise()`中的预定代码实际运行时，没有回调附加到延期者的承诺上。在调用了`brokenPromise()`之后，更多的代码被安排来将一个解析回调和一个进度回调附加到承诺上。当预定的代码运行时，进度回调被完全忽略，而解析回调接收它的值。为什么呢？因为进度回调是在调用 deferred 的`notify()`方法后调度的代码中添加的。根据 Promises/A+规范，当新的回调被添加到一个可调用对象中时，解决和拒绝肯定会被传播，但是 Q 将通知视为“实时”事件，只传播到通知时附加的回调。

### 一切都结束了

为了进一步模仿同步代码约定，Q 提供了`catch()`和`finally()`方法，它们在同步的结构化异常处理中并行处理各自的对应方法。

`catch()`方法实际上是`then(null, onRejection)`的别名。和`then()`一样，`catch()`不会中断承诺链，但是它允许开发人员处理承诺链中任意点的错误。清单 14-25 中的代码使用`catch()`来拦截潜在的 HTTP 故障。因为`catch()`本身返回一个承诺，它的回调可以返回任何值(或者抛出另一个错误)以便在承诺链中稍后处理。

Listing 14-25\. Catching Errors in a Promise Chain

`// example-016/index.js`

`'use strict';`

`var Q = require('q');`

`var api = require('./api');`

`var InvalidTeamError = require('./invalid-team-error');`

`function loadTeamRoster(teamID) {`

`// api.get() returns a promise`

`return api.get('/team/' + teamID + '/roster')`

`.catch(function (err) {`

`/*`

`* throw a meaningful exception rather than`

`* propagate an HTTP error`

`*/`

`if (err.statusCode === 404) {`

`throw new InvalidTeamError(teamID);`

`}`

`});`

`}`

`loadTeamRoster(123).then(function (roster) {`

`console.log(roster);`

`}).catch(function (err) {`

`console.error(err.message);`

`});`

`finally()`方法的行为类似于`then()`,但有一点需要注意:它可能不会改变它接收到的任何值或错误，尽管它可能会返回一个全新的承诺，并沿着承诺链进行传播。如果它没有返回任何东西，那么它收到的原始值或错误将被传递。

`finally()`方法的真正目的反映了`try/catch`块的`finally`部分的目的。它允许代码在执行线程继续执行之前清理资源。清单 14-26 展示了如何使用`finally()`块关闭数据库连接。不管连接或更新是否成功，`finally()`回调中的代码将一直运行，如果数据库句柄保持打开，就清理它。

Listing 14-26\. Cleaning Up Resources in a Promise Chain

`// example-017/index.js`

`'use strict';`

`var Q = require('q');`

`var db = require('./database');`

`var user = {`

`id: 1001,`

`name: 'Nicholas Cloud',`

`occupation: 'Code Monkey'`

`};`

`db.connect().then(function (conn) {`

`return conn.user.update(user)`

`.finally(function () {`

`if (conn.isOpen) {`

`conn.close();`

`}`

`});`

`});`

当调用`finally()`时，它实际上并没有终止承诺链。但是在代码中可能会有这样的地方，当不再添加处理程序时，您希望在一系列异步操作中处理最终值或错误。这可以通过多种方式实现。终止一个链的最明显的方法是通过忽略由`then()`创建的最终承诺来简单地中止它。不幸的是，该承诺可能已经被承诺链中的上游代码拒绝。这意味着 Q 将保留 promise 链中产生的任何错误，如果将来添加了拒绝回调，这些错误将不会被处理。如果一个承诺链在没有拒绝回调的情况下被“终止”,如清单 14-27 所示，错误永远不会被报告——它消失在以太中——并且解决回调永远不会被执行。

Listing 14-27\. Improperly Terminating a Promise Chain

`// example-018/index01.js`

`'use strict';`

`var Q = require('q');`

`function crankyFunction() {`

`var d = Q.defer();`

`process.nextTick(function () {`

`d.reject(new Error('get off my lawn!'));`

`});`

`return d.promise;`

`}`

`// no rejection callback to display the error`

`crankyFunction().then(function (value) {`

`console.log('never resolved');`

`});`

为了应对这一点，Q 创建的承诺也有一个`done()`方法，它不返回承诺，并在事件循环的未来回合中抛出任何未处理的错误，以通过其他方式解决。清单 14-28 展示了这种方法。

Listing 14-28\. Terminating a Promise Chain with `done()`

`// example-018/index02.js`

`crankyFunction().done(function (value) {`

`//...`

`});`

即使没有提供拒绝回调，JavaScript 上下文仍然会终止，因为 Q 的`done()`方法会自动抛出一个未处理的错误。清单 14-29 中的控制台输出显示了如果`crankyFunction()`的承诺链被`done()`方法终止会发生什么。

Listing 14-29\. Unhandled Error Thrown by `done()`

`$ node index02.js`

`/.../node_modules/q/q.js:126`

`throw e;`

`^`

`Error: get off my lawn!`

`at /.../code/q/example-018/index02.js:7:14`

`at process._tickCallback (node.js:419:13)`

`at Function.Module.runMain (module.js:499:11)`

`at startup (node.js:119:16)`

`at node.js:906:3`

## 带 Q 的流量控制

承诺链是扁平化异步的、基于回调的 API 的极好方法。它们还以自己的方式模拟开发人员在同步代码中熟悉的结构化异常处理模式。这些特性简化了基于承诺的代码中的流控制，但是可以利用一点创造性来为以下更复杂的流利用承诺，在这些流中，可以将许多异步操作“分组”并作为一个整体对待:

*   顺序流:独立的异步操作被调度和执行，一次一个，每个操作在前一个操作完成后开始。
*   并行流:独立、异步的操作同时被调度，并聚合所有结果。
*   管道流:一次执行一个相关的异步操作，每个操作都依赖于前一个操作中创建的值。

在每种类型的流中，拒绝一个操作通常会触发流的失败。顺序流关注的是副作用，而不是值(这意味着它实际上并不获取或创建将在以后使用的数据)，尽管它可以在必要时聚合获取的数据。并行流聚集来自许多不同异步操作的数据，并在所有操作完成时交付其结果。管道流通过一系列操作传递一些数据，因此至少有一个操作将获取或创建数据，并且在流的末尾将有一些值要处理。

### 顺序流程

清单 14-30 中的函数代表了 web 应用共有的一系列步骤。他们更改用户的密码。当然，每个步骤都是高度简化的，但是三个基本步骤必须按顺序完成:

Change the actual password.   Notify the user (probably via e-mail) that their password has been changed.   Because our company is a Good Corporate Citizen, it forwards the password on to the National Security Agency (NSA).   Listing 14-30\. Functions Executed in a Sequential Flow

`// example-019/index.js`

`function changePassword(cb) {`

`process.nextTick(function () {`

`console.log('changing password...');`

`cb(null);`

`});`

`}`

`function notifyUser(cb) {`

`process.nextTick(function () {`

`console.log('notifying user...');`

`var randomFail = Date.now() % 2 === 0;`

`cb(randomFail ? new Error('fail!') : null);`

`});`

`}`

`function sendToNSA(cb) {`

`process.nextTick(function () {`

`console.log('sending to NSA...');`

`cb(null);`

`});`

`}`

每个操作的功能都是异步的，并且符合标准的 Node.js 回调模式。在清单 14-30 的例子中，`changePassword()`和`sendToNSA()`函数总是成功，但有趣的是，根据计算的值，`notifyUser()`函数有时成功，有时失败。

为了在一个连续的承诺流中编排这三个操作，它们首先以适当的执行顺序被添加到一个“步骤”数组中。通过调用不带任何参数的`Q`创建一个“空”承诺(`lastPromise`);这将是连续承诺链中第一个已解决的承诺。

在清单 14-31 中，代码遍历步骤数组，将每个步骤封装在一个承诺中。对于每次迭代，它调用`lastPromise`上的`then()`方法，并将结果——一个新生成的承诺——赋回给`lastPromise`变量。(这在一个循环中建立了一个承诺链。)

在每个解析回调中，代码通过将当前的“步骤”(清单 14-30 中定义的函数之一)传递给`Q.denodeify()`，将其转换为承诺。同样可以通过设置一个延迟并使用`deferred.makeNodeResolver()`来手动完成，如清单 14-11 所示，但是`Q.denodeify()`简化了这个过程。结果是一个承诺，它可以作为承诺链中的下一步从解析回调中返回。

Listing 14-31\. Orchestrating a Sequential Flow with Promises

`// example-019/index.js`

`var Q = require('q');`

`var steps = [changePassword, notifyUser, sendToNSA];`

`var lastPromise = Q();`

`steps.forEach(function (step) {`

`lastPromise = lastPromise.then(function () {`

`/*`

`* denodeify and invoke each function step`

`* to return a promise`

`*/`

`return Q.denodeify(step)();`

`});`

`});`

`lastPromise.done(function () {`

`console.log('all done');`

`}, function (err) {`

`console.error(err);`

`});`

最后，解决和拒绝回调被附加到循环创建的最后一个承诺上。

当下一个预定循环执行时，第一步将开始。当它解决时，将调用链中的下一个承诺，依此类推，直到到达顺序流的末尾。如果在链中的任何一点发生错误，它将立即导致调用最终拒绝回调。(没有中间拒绝回调；当任何一个步骤失败时，顺序流应该失败。)如果所有步骤都解决了，最终的解决回调将输出控制台消息:`all done`。

### 平行流

应用通常会从各种来源获取数据，然后作为一个统一的整体发送给某个客户端。在清单 14-32 中，用户数据和美国各州的列表被同时获取，也许是为了一个网页，用户可以在这个网页上更改他或她的邮寄地址。

Listing 14-32\. Functions Executed in a Parallel Flow

`// example-20/index01.js`

`function getUser(id, cb) {`

`process.nextTick(function () {`

`cb(null, {id: id, name: 'nick'});`

`});`

`}`

`function getUSStates(cb) {`

`process.nextTick(function () {`

`cb(null, ['MO', 'IL' /*, etc.*/]);`

`});`

`}`

因为这两个异步函数彼此无关，所以应该同时调度它们(而不是一个等待另一个完成)，这是有意义的。Q 的效用函数`all()`接受一组要同时调度的承诺，但是由于清单 14-32 中的函数还不是承诺，它们必须用 Q 的一个函数调用方法进行转换。因为函数符合 Node.js 回调签名，清单 14-33 中的代码将每个函数传递给`Q.nfcall()` (node-function-call)，后者将每个函数包装在承诺中，使用延迟来提供适当的回调。因为`getUser()`函数接受单个数据参数，所以在创建`getUser()`承诺时，用户 ID 必须作为第二个参数传递给`Q.nfcall()`。在内部调用时，q 会将用户 ID 作为第一个参数绑定到`getUser()`函数。

q 的`all()`函数本身返回一个承诺，这个承诺将用一个值数组来解析。数组中每个值的顺序位置将对应于传递给`Q.all()`的数组中承诺的顺序。在这种情况下，用户数据将占用索引 0，而美国州数组将占用索引 1。

如果任何承诺中出现错误，将调用聚合承诺的拒绝回调。

Listing 14-33\. Orchestrating a Parallel Flow with Promises

`// example-20/index01.js`

`var Q = require('q');`

`Q.all([`

`Q.nfcall(getUser, 123),`

`Q.nfcall(getUSStates)`

`]).then(function (results) {`

`console.log('user:', results[0]);`

`console.log('states:', results[1]);`

`}, function (err) {`

`console.error('ERR', err);`

`});`

因为访问数组中的值是笨拙的，所以可以用`spread()`方法继续一个承诺，该方法的操作与`then()`相同，除了它将结果数组“分解”成实际的单个参数，如清单 14-34 所示。

Listing 14-34\. Spreading Results

`// example-20/index02.js`

`var Q = require('q');`

`Q.all([`

`Q.nfcall(getUser, 123),`

`Q.nfcall(getUSStates)`

`]).spread(function (user, states) {`

`console.log('user:', user);`

`console.log('states:', states);`

`}, function (err) {`

`console.error('ERR', err);`

`});`

q 还提供了一个伴随函数`Q.allSettled()`，它的行为类似于`Q.all()`，但有一些关键的不同。首先，它将总是调用聚合承诺的解析回调。其次，每个值将是一个具有`state`属性的对象，该属性将报告创建该值的承诺的实际状态，以及依赖于`state`的值的下列属性之一:

*   `value`，如果承诺解决，它将包含由承诺创建的数据
*   `reason`，包含承诺被拒绝时产生的任何错误

选择使用`Q.all()`还是`Q.allSettled()`将取决于应用代码的性质，但是两者都可以用来创建并行流。

### 管道流动

当一组数据需要根据一些顺序规则集进行转换时，管道流非常有用。管道和前面介绍的顺序流之间的区别在于，管道中的每一步都将数据传递给下一步，而顺序流主要关注的是创建一系列线性副作用。

清单 14-35 中的管道函数代表了一个简化的过滤系统，也许是为一个寻找客户人才的招聘机构。`loadCandidates()`函数将“获取”一个可能的候选列表，其他函数将负责根据一些标准来减少选择。注意`filterBySkill()`和`groupByStates()`实际上是工厂函数。它们接受一些配置参数(所需的技能和状态)，然后返回一个函数，该函数接受要在管道中使用的 Node.js 回调。

Listing 14-35\. Functions Executed in a Pipeline Flow

`// example-021/index.js`

`function loadCandidates(cb) {`

`console.log('loadCandidates', arguments);`

`process.nextTick(function () {`

`var candidates = [`

`{name: 'Nick', skills: ['JavaScript', 'PHP'], state: 'MO'},`

`{name: 'Tim', skills: ['JavaScript', 'PHP'], state: 'TN'}`

`];`

`cb(null, candidates);`

`});`

`}`

`function filterBySkill(skill) {`

`return function (candidates, cb) {`

`console.log('filterBySkill', arguments);`

`candidates = candidates.filter(function (c) {`

`return c.skills.indexOf(skill) >= 0;`

`});`

`cb(null, candidates);`

`};`

`}`

`function groupByStates(states) {`

`var grouped = {};`

`states.forEach(function (state) {`

`grouped[state] = [];`

`});`

`return function (candidates, cb) {`

`console.log('groupByStates', arguments);`

`process.nextTick(function () {`

`candidates.forEach(function (c) {`

`if (grouped.hasOwnProperty(c.state)) {`

`grouped[c.state].push(c);`

`}`

`});`

`cb(null, grouped);`

`});`

`};`

`}`

`loadCandidates()`函数被直接添加到`steps`数组中，但是`filterBySkill()`和`groupByStates()`函数是用它们的初始值调用的。

像串行和并行流一样，管道流使用承诺链来协调执行顺序。然而，在清单 14-36 中，每个步骤创建的结果——传递给每个承诺的解析回调的值——被放入一个数组中，并作为参数传递给序列中的下一个承诺。在并行流程示例中，`Q.nfcall()`用于调用每个步骤；在这个例子中，使用了`Q.nfapply()`(节点-功能-应用)。每个调用都模仿其本地 JavaScript 对应物(`Function.prototype.call()`和`Function.prototype.apply()`)，这就是为什么使用数组将结果传递给每个步骤，而不是将结果作为直接参数传递。这是必要的，因为管道的第一步`loadCandidates()`不接受任何参数(除了回调)。向`Q.nfapply()`传递一个空数组可以确保函数被正确调用。

Listing 14-36\. Orchestrating a Pipeline Flow with Promises

`// example-021/index.js`

`var Q = require('q');`

`var steps = [`

`loadCandidates,`

`filterBySkill('JavaScript'),`

`groupByStates(['MO', 'IL'])`

`];`

`var lastPromise = Q();`

`steps.forEach(function (step) {`

`lastPromise = lastPromise.then(function (result) {`

`var args = [];`

`if (result !== undefined) {`

`args.push(result);`

`}`

`return Q.nfapply(step, args);`

`});`

`});`

`lastPromise.done(function (grouped) {`

`console.log('grouped:', grouped);`

`}, function (err) {`

`console.error(err);`

`});`

当管道完成时，传递给最后一个异步回调的最后一个值将是传递给`done()`解析回调的值。如果任何异步操作产生错误，将调用拒绝回调。

对于清单 14-35 中的每个异步函数，每个回调都传递一个值。即使 Promises/A+规范规定只能将一个值作为解析参数传递，也可以将多个值传递给这些回调。q 通过将传递给异步函数回调的所有值打包成一个数组，然后传递给 promise 的 resolution 回调，缓解了这种差异。然后，这个数组需要被传递给`Q.nfapply()`，因为它包含了所有要用作下一个函数步骤的参数的数据。

## 摘要

回调是处理异步代码的标准机制。它们为开发人员提供了一种控制流机制，以便在事件循环的下一次循环之后“继续”执行。但是回调会很快变成嵌套的、复杂的、难以管理的。

使用像 Q 这样的 promise 库来封装异步操作，来“扁平化”代码，可以极大地改进代码库。q 能够自动传播值和错误，以异步方式链接回调，在长时间运行的异步操作中报告进度，并在承诺链结束时处理未处理的错误，这使它成为任何开发人员工具箱中的强大工具。

q 可以用来管理琐碎的、线性的程序流，但是稍加创新也可以适应更复杂的流。本章研究了顺序流、并行流和管道流，但是 Q 的实用方法在编排其他流时为开发人员提供了额外的灵活性。

## 相关资源

*   问: [`https://github.com/kriskowal/q`](https://github.com/kriskowal/q)
*   承诺/A+规格: [`https://promisesaplus.com/`](https://promisesaplus.com/)